[build-system]
requires = ["setuptools>=75.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "davidia-example-client"
description = "Example frontend for Davidia"
readme = "Static files to serve for an example Davidia plot client"
dynamic = ["version"]
license = "MIT"
maintainers = [
    {name = "Data Analysis group", email = "dataanalysis@diamond.ac.uk"}
]
classifiers = [
    "Environment :: Web Environment",
    "Natural Language :: English",
    "Programming Language :: JavaScript",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">= 3.11"
dependencies = [
    "davidia==1.2.0",
    "pydantic",
    "numpy",
]

[project.scripts]
dvd-demo = "davidia.demos.simple:start_and_run_all_demos"

[project.urls]
repository = "https://github.com/DiamondLightSource/davidia"

[project.entry-points."davidia.plugins"]
myplugin = "example.plugin:ExampleSourcePlugin"

[tool.setuptools]
packages = ["davidia.client", "davidia.client.assets", "example"]

[tool.setuptools.package-dir]
"example" = "src/example"
"davidia.client" = "sdist"
"davidia.client.assets" = "sdist/assets"

[tool.setuptools.dynamic]
version = {attr = "example.__version__"} 

[tool.setuptools.package-data]
"*" = ["*.png", "*.ico", "*.html", "*.txt", "*.json", "*.css", "*.js"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["E501", "W505"]
extend-select = ["I001"]

[tool.ruff.lint.isort]
known-third-party = ["davidia"]

[tool.ruff.lint.mccabe]
max-complexity = 10
