name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["24.x"]
        python-version: ["3.12"]
 
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          run_install: |
            args: [ --force ]

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install server dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi

      - name: Generate OpenAPI JSON
        run: |
          PYTHONPATH=server python server/davidia/generate_openapi.py

      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Build storybook
        id: build
        run: |
          pnpm run docs && pnpm build:storybook

      - name: Upload Pages artifact
        id: upload
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: storybook/storybook-static

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        with:
          token: ${{ github.token }}